site_name: Infrastructure Demo API
site_description: API provider for the infrastructure teams demo projects
repo_url: https://github.com/PureGymGroup/infra-demo-api
edit_uri: edit/main/docs
nav:
  - Overview:
      - What is Backstage?: README.md
plugins:
  - techdocs-core
