---

trigger:
  paths:
    include:
    - docs/README.md

pool: puregym-uks-ubuntu

variables: 
  - group: Techdocs

stages:
  - stage: build_stage
    displayName: Build
    jobs:
      - job: build_docs_job
        displayName: Build Techdocs
        steps:
        - task: NodeTool@0
          displayName: 'Use Node 16.x'
          inputs:
            versionSpec: 16.x
        - bash: |
            docker pull spotify/techdocs:v1.0.3
            npx @techdocs/cli generate --source-dir docs/README.md
            npx @techdocs/cli publish --publisher-type azureBlobStorage --storage-name techdocs --entity $(Build.Repository.Name)/src --azureAccountName $(azureAccountName) --azureAccountKey $(azureAccountKey)
          displayName: 'Bash Script'