---

pool: puregym-uks-ubuntu

stages:
  - stage: build_stage
    displayName: Build
    jobs:
      - job: build_docs_job
        displayName: Build Techdocs
        steps:
        - task: NodeTool@0
          displayName: 'Use Node 16.x'
          inputs:
            versionSpec: 16.x
        - bash: |
            docker pull spotify/techdocs:v1.0.3
            npx @techdocs/cli generate
          displayName: 'Bash Script'