---

pool: puregym-uks-ubuntu-aks

stages:
  - stage: build_docs_stage
    displayName: Build Documention
    jobs:
      - job: build_docs_job
        displayName: Build Documentation
        workspace:
          clean: all
        steps:
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: <Name of the Azure Resource Manager service connection>
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                STORAGE_ACCOUNT_NAME="stagingbackstagestouks"
                STORAGE_ACCOUNT_KEY=$(az storage account keys list -n ${STORAGE_ACCOUNT_NAME} --subscription c4688de8-0fd2-4826-b0cf-fe637dfa7e6b | jq -r .[0].value)
                techdocs-cli generate --source-dir ./docs --output-dir ${BUILD_ARTIFACTSTAGINGDIRECTORY}
                techdocs-cli publish --directory "${BUILD_ARTIFACTSTAGINGDIRECTORY}" --publisher-type "azure" --azureAccountName "${STORAGE_ACCOUNT_NAME}" --azureAccountKey "${STORAGE_ACCOUNT_KEY}" --storage-name "techdocs" --entity "default/api/infra-demo-api"