---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: infra-demo-api
  links:
    - url: https://demo.pureiac.com/api/v1
      title: Root API
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:/docs
spec:
  type: openapi
  lifecycle: experimental
  owner: developers_-_platform_team
  system: infrastructure-demo
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Test API
      license:
        name: MIT
    servers:
      - url: http://demo.pureiac.com/api/v1
    paths:
      /test:
        get:
          summary: List all demo tests

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Example-ADR
  description: An example ADR
  annotations:
    backstage.io/adr-location: ./adrs
spec:
  type: adr
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-website
  description: The backstage frontend interface
  annotations:
    dev.azure.com/project: Puregym
    dev.azure.com/build-definition: Infrastructure and tooling team
    backstage.io/techdocs-ref: dir:/docs
  links:
    - title: Backstage Prod
      url: https://backstage.puregym.com
    - title: Backstage Staging
      url: https://backstage.puregymuk.dev
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage

---