---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: infrastructure-demo
spec:
  owner: IaT

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: infra-demo-api
spec:
  type: openapi
  lifecycle: experimental
  owner: IaT
  system: infrastructure-demo
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Test API
      license:
        name: MIT
    servers:
      - url: http://demo.pureiac.com/v1
    paths:
      /test:
        get:
          summary: List all demo tests
